In [143]:
import numpy as np
from random import sample

In [144]:
#centroid1=[]
#centroid2=[]
#centroid3=[]
cluster1=[]
cluster2=[]
cluster3=[]
points = [[2,4],[4,3],[5,2],[9,3],[6,12],[10,13],[20,5],[25,8],[21,10],[20,13],[27,9],[12,12]]
centroid1=sample(points,1)
centroid2=sample(points,1)
centroid3=sample(points,1)
c_point = [0]*len(points)

In [145]:
centroid1

[[20, 13]]

In [146]:
centroid2

[[4, 3]]

In [147]:
centroid3

[[2, 4]]

In [148]:
def euc_dist(p1,p2):
    return np.sqrt((np.square(p1[0]-p2[0])+np.square(p1[1]-p2[1])))

In [149]:
def clustering(centroid1,centroid2,centroid3):
    dist=[0]*3
    for i in points:
        dist[0]=euc_dist(i,centroid1[0])
        dist[1]=euc_dist(i,centroid2[0])
        dist[2]=euc_dist(i,centroid3[0])
        closest=dist.index(min(dist))+1
        if(closest==1):
            cluster1.append(i)
        if(closest==2):
            cluster2.append(i)
        if(closest==3):
            cluster3.append(i)
    centroid1=np.mean(cluster1, axis=0)
    centroid2=np.mean(cluster2, axis=0)
    centroid3=np.mean(cluster3, axis=0)
    #cluster1=null
    #cluster2=null
    #cluster3=null
    return centroid1,centroid2,centroid3

In [150]:
centroid1,centroid2,centroid3=clustering(centroid1,centroid2,centroid3)

In [151]:
centroid1

array([19.28571429, 10.        ])

In [152]:
centroid2

array([6.        , 2.66666667])

In [153]:
centroid3

array([4., 8.])